import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter, Zen_Dots } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const zenDot = Zen_Dots({
  weight: ["400"],
 subsets:['latin'],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
